apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: host-metering-rules-template
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: PrometheusRule
  metadata:
    labels:
      tenant: rhel
    name: host-metering-recording-rules
  spec:
    groups:
      - name: host-metering
        interval: 10m
        limit: 0
        rules:
          - record: cpu_rate:10m
            expr: |
              rate(system_cpu_logical_count[10m])
          - record: cpu_count:10m
            expr: |
              count_over_time(system_cpu_logical_count[10m])
          - record: cpu_usage:10m
            expr: |
              cpu_rate:10m / cpu_count:10m
          - record: min_cpu_logical_count:10m
            expr: |
              group without (swatch_placeholder_label) (
                min_over_time(
                  system_cpu_logical_count{
                  product=~".*(^|,)(204)($|,).*",
                  billing_model="marketplace",
                  support=~"Premium|Standard|Self-Support|None|"
                  }[10m]
                )
              )
            labels:
              rulesVersion: v0
